include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - "**/*.g.dart"
    - "**/*.schema.dart"

linter:
  rules:
    file_names: false
