name: backend_playground
version: 0.0.1+1
publish_to: none
description: A backend playground

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  dart_frog: ^0.3.6
  envied: ^0.3.0
  get_it: ^7.3.0
  grpc: ^3.1.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  protobuf: ^2.1.0
  stormberry: ^0.13.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^4.0.0+1

dependency_overrides: 
  meta: ^1.9.1
